/* --- START OF FILE app/dashboard/legal/page.tsx --- */

import React from "react";

export default function LegalTerminalMatrix() {
  return (
    <div className="w-full h-full flex flex-col relative z-10 max-w-6xl mx-auto gap-8">
      
      {/* Page Header - Cyan Intent for Info/System */}
      <div className="w-full flex flex-col border-b border-[#00BFFF]/30 pb-4">
        <div className="flex flex-row items-center gap-4">
          <h1 className="font-orbitron text-2xl md:text-3xl text-[#00BFFF] font-bold uppercase tracking-[0.15em] drop-shadow-[0_0_8px_rgba(0,191,255,0.6)]">
            Legal Terminal
          </h1>
          <span className="px-3 py-1 bg-[#00BFFF]/20 border border-[#00BFFF]/50 text-[#00BFFF] text-[10px] font-orbitron uppercase tracking-widest rounded animate-pulse">
            Protocol // Governance_Enforced
          </span>
        </div>
        <p className="font-inter text-xs text-[#8B949E] uppercase tracking-widest mt-2">
          End User License Agreements & Studio Policies
        </p>
      </div>

      {/* LEGAL DOCUMENTATION GRID */}
      <div className="w-full grid grid-cols-1 md:grid-cols-2 gap-8">
        
        {/* Module: Handy EULA */}
        <div className="glass-panel flex flex-col p-8 border-l-4 border-l-[#00BFFF] hover:border-l-[#00FFFF] hover:bg-[#00BFFF]/5 transition-all duration-300">
          <span className="font-mono text-[10px] text-[#00BFFF] uppercase tracking-[0.2em] mb-6 border-b border-[#00BFFF]/20 pb-2">
            [ SECTOR // HANDY_EULA ]
          </span>
          <h3 className="font-orbitron text-xl text-[#E6EDF3] tracking-widest uppercase mb-4">
            Software Usage Rights
          </h3>
          <p className="font-inter text-sm text-[#8B949E] leading-relaxed mb-4">
            The <strong className="text-[#E6EDF3]">HANDY Editor Utility</strong> is licensed, not sold. Harrison Interactive LLC retains absolute proprietary ownership of the hybrid Python-Blueprint architecture.
          </p>
          <p className="font-inter text-sm text-[#8B949E] leading-relaxed">
            <strong className="text-[#E6EDF3]">Grant of License:</strong> Licensed operators are authorized to use Handy within the Unreal Engine 5 Editor to generate Data Assets, Actor Blueprints, and Level data. While you own the <em className="text-[#00BFFF] not-italic">output</em> generated by the tool, the redistribution, de-compilation, or public mirroring of the <code className="text-[#00BFFF] bg-[#00BFFF]/10 px-1 rounded">Content/Handy/</code> logic core or its associated <code className="text-[#00BFFF] bg-[#00BFFF]/10 px-1 rounded">.py</code> scripts is strictly prohibited and constitutes a breach of the Fab Marketplace license.
          </p>
        </div>

        {/* Module: Economy Policies (Crimson Intent for RMT) */}
        <div className="glass-panel flex flex-col p-8 border-l-4 border-l-[#DC143C] hover:border-l-[#FF0000] hover:bg-[#DC143C]/5 transition-all duration-300">
          <span className="font-mono text-[10px] text-[#DC143C] uppercase tracking-[0.2em] mb-6 border-b border-[#DC143C]/20 pb-2">
            [ SECTOR // ECONOMY_POLICIES ]
          </span>
          <h3 className="font-orbitron text-xl text-[#E6EDF3] tracking-widest uppercase mb-4">
            RMT & Symbiotic Economy
          </h3>
          <p className="font-inter text-sm text-[#8B949E] leading-relaxed mb-4">
            The <strong className="text-[#E6EDF3]">Blood-Yield Real Money Trading (RMT) Marketplace</strong> is a secure environment for the exchange of <strong className="text-[#E6EDF3]">Cold Iron</strong> and <strong className="text-[#E6EDF3]">Soul Essence</strong>.
          </p>
          <p className="font-inter text-sm text-[#8B949E] leading-relaxed">
            <strong className="text-[#DC143C]">Authority:</strong> Harrison Interactive reserves the absolute right to audit transactions, freeze assets, or revoke <strong className="text-[#E6EDF3]">Verified Signatory Badges</strong> if an operator is found exploiting Soul-Blight decay cycles or using unauthorized automation to gain an unfair harvest advantage. Participation in the economy constitutes agreement to our anti-fraud telemetry protocols.
          </p>
        </div>

        {/* Module: Privacy & Encryption */}
        <div className="glass-panel flex flex-col p-8 border-l-4 border-l-[#00BFFF] hover:border-l-[#00FFFF] hover:bg-[#00BFFF]/5 transition-all duration-300">
          <span className="font-mono text-[10px] text-[#00BFFF] uppercase tracking-[0.2em] mb-6 border-b border-[#00BFFF]/20 pb-2">
            [ SECTOR // PRIVACY_ENCRYPTION ]
          </span>
          <h3 className="font-orbitron text-xl text-[#E6EDF3] tracking-widest uppercase mb-4">
            Data & Telemetry
          </h3>
          <p className="font-inter text-sm text-[#8B949E] leading-relaxed mb-4">
            Harrison Interactive adheres to a <strong className="text-[#E6EDF3]">Minimal Data Footprint</strong> policy. We do not store localized financial records or private user credentials on studio hardware.
          </p>
          <p className="font-inter text-sm text-[#8B949E] leading-relaxed">
            <strong className="text-[#E6EDF3]">Ultimate Tier Connectivity:</strong> When utilizing the "Bring Your Own Brain" (BYOB) routing, your third-party LLM API keys are processed locally through the Python bridge. Harrison Interactive does not see, store, or log the data streams transmitted between your workstation and your chosen AI provider.
          </p>
        </div>

        {/* Module: System Liability */}
        <div className="glass-panel flex flex-col p-8 border-l-4 border-l-[#00BFFF] hover:border-l-[#00FFFF] hover:bg-[#00BFFF]/5 transition-all duration-300">
          <span className="font-mono text-[10px] text-[#00BFFF] uppercase tracking-[0.2em] mb-6 border-b border-[#00BFFF]/20 pb-2">
            [ SECTOR // SYSTEM_LIABILITY ]
          </span>
          <h3 className="font-orbitron text-xl text-[#E6EDF3] tracking-widest uppercase mb-4">
            Software Disclaimer
          </h3>
          <p className="font-inter text-sm text-[#8B949E] leading-relaxed mb-4">
            Harrison Interactive software is provided <strong className="text-[#00BFFF]">"AS IS"</strong> without warranty of any kind, express or implied. Game development is an inherently unstable process; we are not liable for project data loss, corruption, or performance degradation resulting from the use of our tools.
          </p>
          <p className="font-inter text-sm text-[#8B949E] leading-relaxed">
            <strong className="text-[#E6EDF3]">Version Lock:</strong> Handy is optimized strictly for <strong className="text-[#00BFFF]">Unreal Engine 5.4 Stable</strong>. Usage on experimental engine branches or "Day 0" updates is at the operator's own risk.
          </p>
        </div>

      </div>
    </div>
  );
}

/* --- END OF FILE app/dashboard/legal/page.tsx --- */